version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: roquete
      MYSQL_DATABASE: Prueba2
      MYSQL_USER: roque
      MYSQL_PASSWORD: roquete
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: roquete
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local